---
title: Minh Tuan Nguyen
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: Welcome to my page
url: https://minhtuannguyen.github.io
baseurl: "/"
google_analytics: UA-35260710-2
disqus_shortname: mtnguyensblog
author:
  name: Minh Tuan Nguyen
  email: minhtuannguyen2704@gmail.com
  twitter_username: minhtuan_nguyen
  github_username: minhtuannguyen
  linkedin_username: minh-tuan-nguyen-14154733
  xing_username: MinhTuan_Nguyen5
destination: _site
paginate: 10
permalink: "/:year/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
gems:
- jekyll-paginate
exclude:
- README.md
- vendor
- Gemfile
- Gemfile.lock
- screenshot.png
