# Site settings
title: Minh Tuan Nguyen
description: 'Welcome to my page'
url: 'http://minhtuannguyen.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Minh Tuan Nguyen'
  email: minhtuannguyen2704@gmail.com
  twitter_username: minhtuan_nguyen
  github_username:  minhtuannguyen
  linkedin_username:  minh-tuan-nguyen-14154733
  xing_username: MinhTuan_Nguyen5

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
