# Site settings
title: Mudit Agrawal
description: 'Welcome to my page'
url: 'https://mudit313.github.io'
baseurl: '/'
google_analytics: 'UA-35260710-2'
disqus_shortname: 'mtnguyensblog'

author:
  name: 'Mudit Agrawal'
  email: muditag313@gmail.com
  github_username:  mudit313
  linkedin_username:  mudit313
  facebook_username: muddu313

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'vendor', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
